# Generated by Django 4.1 on 2022-09-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_category", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homecategory",
            name="restaurant_category_slug",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="homecategory",
            name="restaurant_category_type",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
