# Generated by Django 4.1 on 2022-09-03 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home_category", "0002_alter_homecategory_restaurant_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homecategory",
            name="list_group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                help_text="홈 카테고리가 포함될 목록 그룹 (A/B 테스트 그룹 설정 필요 시 변경, 생성 후 수정 불가능)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home_category.homecategorylistgroup",
            ),
        ),
        migrations.AlterField(
            model_name="homecategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                help_text="상위 홈 카테고리",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home_category.homecategory",
            ),
        ),
        migrations.AlterField(
            model_name="homecategoryimage",
            name="home_category",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_set",
                to="home_category.homecategory",
            ),
        ),
        migrations.AlterField(
            model_name="homecategorylistgroup",
            name="created_by",
            field=models.ForeignKey(
                db_constraint=False,
                db_index=False,
                default=None,
                help_text="그룹을 생성한 사용자",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
